### PR TITLE
[FIX] Fixed #261. Retryable Job Exception must also throw the excepti…

### LINKED ISSUE #261: RetryableJobError does not Rollback Transaction
Hi all,

i have an issue with the RetryableJobError - when i raise this error in the middle of a job (eg. some data already got changed), then it will not issue a Rollback - because it does not raise the error forward to the main odoo code - so the transaction will get commited.

Is this really a wanted behaviour ?

It would be great if we could add here an option to the RetryableJobError to rollback the transaction..

Code in question is here:
https://github.com/OCA/queue/blob/a5afdb344b21c9669f8625afe19920daa4590495/queue_job/controllers/main.py#L108

### PR DESCRIPTION
**Pull request by agent-z28**
…on and rollback

Backport from https://github.com/OCA/queue/commit/ca2af1582f8d8f0b770afe392ada94991319d2f9

### CODE REVIEW

**Comment by guewen** [comment]
Thanks! Could you fix the travis build please? It complains about the lint.

**Comment by guewen** [comment]
@agenterp I modified the change on #312 and #311, could you include it in your backport please?

**Comment by StefanRijnhart** [comment]
@agenterp what do you think of the original PRs? Can you review them, and if you agree with the changes, update this PR?

**Comment by agent-z28** [comment]
> @agenterp what do you think of the original PRs? Can you review them, and if you agree with the changes, update this PR?

@StefanRijnhart yes i can take care now

**Comment by StefanRijnhart** [comment]
Sorry for the delay. Thanks for taking the last change from the other PR. Now, about this PR: the diff looks different from the other PRs, I believe because you seem to be taking other changes as well, such as https://github.com/OCA/queue/commit/b511c3af52d8735751b1933adbf2e6771a4381f5. If that is the case, can you update your branch and cherry pick these commits so that authorship and history is preserved?

**Pull request closed without merging**
