### PR TITLE
[10.0] add queue job subscribe 

### PR DESCRIPTION
**Pull request by GillesTephaneMeyomesse**
As suggered by @guewen  and approved by @sbidoul in https://github.com/OCA/connector/pull/250 i move this module in queue repository.
old name connecto_job_subscribe renamed queue_job_subscribe

### CODE REVIEW

**Comment by elicoidal** [comment]
Please adapt and correct the README (malformed URL)

**Comment by GillesTephaneMeyomesse** [comment]
@elicoidal Of course for the next commit

**Comment by guewen** [comment]
It includes more commits than expected, could you check?

**Comment by sbidoul** [comment]
superseded by #26

**Pull request closed without merging**
