### PR TITLE
[12.0][MIG] queue_job_batch

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Standard migration and some little ux improvements: now hide
button is a fa-check button that on click just marks as read
the batch, do not navigate to it and updates immediately
the systray.

Screenshot from 2019-10-31 13-08-05

test_queue_job_batch included in this PR.

cc @etobella 

@Eficent

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM :+1:
Code Review of the changes

**Review by lmignon — APPROVED** [review]
LGTM (Code review only) Thank you @lreficent

**Comment by sbidoul** [comment]
cc/ @sbejaoui @qgroulard

**Review by guewen — APPROVED** [review]

**Pull request merged**
