### PR TITLE
[14.0] mig queue job rebased

### PR DESCRIPTION
**Pull request by sebastienbeau**
The queue job in V14 is ready \o/

### CODE REVIEW

**Review by guewen — APPROVED** [review]
Untested, code looks good. Thanks for handling this 😊

**Comment by t-900-a** [comment]
> Untested, code looks good. Thanks for handling this 😊

Are there any sample modules that I can run to test this?

Trying to do what I can to help this along.

ty

**Comment by guewen** [comment]
@sebastienbeau travis was not triggered, maybe you should amend the last commit?

**Comment by guewen** [comment]
In runbot logs:

```
2020-11-20 15:44:58,072 159 WARNING openerp_test odoo.fields: Field queue.job.record_ids: unknown parameter '_base_type', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
2020-11-20 15:44:58,072 159 WARNING openerp_test odoo.fields: Field queue.job.records: unknown parameter '_base_type', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
2020-11-20 15:44:58,072 159 WARNING openerp_test odoo.fields: Field queue.job.args: unknown parameter '_base_type', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
2020-11-20 15:44:58,072 159 WARNING openerp_test odoo.fields: Field queue.job.kwargs: unknown parameter '_base_type', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
2020-11-20 15:44:58,079 159 WARNING openerp_test odoo.fields: Field queue.job.function.retry_pattern: unknown parameter '_base_type', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
2020-11-20 15:44:58,079 159 WARNING openerp_test odoo.fields: Field queue.job.function.related_action: unknown parameter '_base_type', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
```

I suppose [this](https://github.com/odoo/odoo/blob/ea2d1484fcd91efe89306d6106c01fcdde1c20c3/addons/base_sparse_field/models/models.py#L9-L13) should be done for `_base_type` (used by the field type `JobSerialized`):

`field.type = 'job_serialized' and name == '_base_type'`

I do not quite get this new `_valid_field_parameter`, worth to check what I wrote...

**Comment by guewen** [comment]
Actually, the diff to look at for the `JobSerialized` field is: https://github.com/odoo/odoo/pull/48705/files
`_slots` has been replaced by class attributes. I think `_valid_field_parameter` will not be required if the `JobSerialized` field is changed the same way.

**Comment by guewen** [comment]
> Are there any sample modules that I can run to test this?
> 
> Trying to do what I can to help this along.

Thanks @t-900-a for your proposal to help! 
I guess none of the module using the queue are ported yet, however at least there is now a way to generate dummy jobs when `queue_job` is installed, by doing a `GET` on http://odoo.example.com:8069/queue_job/create_test_job
Maybe not worth to test until the last changes on the `JobSerialized` field are done though?

**Comment by aliencrash** [comment]
> > Are there any sample modules that I can run to test this?
> > Trying to do what I can to help this along.
> 
> Thanks @t-900-a for your proposal to help!
> I guess none of the module using the queue are ported yet, however at least there is now a way to generate dummy jobs when `queue_job` is installed, by doing a `GET` on http://odoo.example.com:8069/queue_job/create_test_job
> Maybe not worth to test until the last changes on the `JobSerialized` field are done though?

I already ported my module and just dependent on this one kkkk.

**Comment by guewen** [comment]
To be continued on #289 :) Thanks!

**Pull request closed without merging**
