### PR TITLE
[14.0][IMP][FWP] queue_job current company

### PR DESCRIPTION
**Pull request by acsonefho**
Forward port of https://github.com/OCA/queue/pull/365
Use the current company to trigger the job (+ add related tests)

### CODE REVIEW

**Comment by acsonefho** [comment]
@rousseldenis

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Comment by guewen** [comment]
Hi, same remarks as on #365. Maybe you could answer on the latter ?

**Comment by sbidoul** [comment]
Hm, I'm not sure it was right to merge this. The proper solution is the queue job context propagation which we merged in #432. @guewen what do you think?

**Comment by guewen** [comment]
Indeed, it shouldn't have been merged

**Pull request merged**
