### PR TITLE
[16.0][MIG] queue_job_subscribe: Migration to 16.0

### PR DESCRIPTION
**Pull request by ramiadavid**

### CODE REVIEW

**Review by kikopeiro — APPROVED** [review]
LGTM (without code review)

:+1:

**Review by julenfl — APPROVED** [review]

**Comment by julenfl** [comment]
Hi @vincent-cowboy @amh-mw , could you take a look to this PR?

Thanks!

**Review by amh-mw — APPROVED** [review]

**Comment by julenfl** [comment]
Hi @guewen @sbidoul @ivantodorovich ,

Could someone please merge this PR, it seems correct

Thank you

**Comment by julenfl** [comment]
Hi @guewen @sbidoul @ivantodorovich ,

Can someone check this PR, it seems correct, sorry for the insistence.

**Review by ivantodorovich — APPROVED** [review]
Hey! I'm not really familiar with this module, but the migration looks good 👍🏻

**Review by asierneiradev — APPROVED** [review]

**Comment by ramiadavid** [comment]
@simahawk can you try again?

**Comment by julenfl** [comment]
@simahawk, can you try the merge again?, thank you very much.

**Comment by julenfl** [comment]
@guewen, can you try the merge again?, thank you very much.

**Pull request merged**
