### PR TITLE
[13.0][queue_job] Update queue_job icon to v13 style.

### PR DESCRIPTION
**Pull request by jvargass**
- Change icon to Odoo 13 style.
- Delete 'icon.svg' file because is not necessary.

### CODE REVIEW

**Review by guewen — APPROVED** [review]
Hi @jvargass, many thanks :)

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You mustn't remove the SVG. It was the source of the design. If you have made the design in bitmap, you must redo it in SVG and export from it. If not, we are losing the editability that SVG has.

**Comment by jvargass** [comment]
> You mustn't remove the SVG. It was the source of the design. If you have made the design in bitmap, you must redo it in SVG and export from it. If not, we are losing the editability that SVG has.

Done :)

**Review by pedrobaeza — APPROVED** [review]
Thanks!

**Comment by guewen** [comment]
Done in #218 
Thanks :)

**Pull request closed without merging**
