### PR TITLE
[12.0][ADD] report_async -- run all reports asyncronously.

### PR DESCRIPTION
**Pull request by kittiu**
The new menu "Report Center" is the central place to host all your reports in one place.
From here, there are 2 ways to launch the report,

1. Run Now - run report immediately as per normal.
2. Run Background - put the report execution to queue job.

Peek 2019-12-08 21-59

TODO:
- [x] Test Script

### CODE REVIEW

**Comment by kittiu** [comment]
@guewen @pedrobaeza 
In your opinion, which repo this module should be?

**Comment by kittiu** [comment]
Ready for review.

**Comment by simahawk** [comment]
what about `OCA/report-engine`?

**Comment by kittiu** [comment]
@simahawk At first I think it is not really the "engine". And the main feature is more with "async". If it is here we don't need to depends on other repo.
But I am also ok, if it make more sense for end user.
Please affirm and I can move. :)

**Comment by simahawk** [comment]
well, is not a generic feature, is a specific feature for reports AFAIS.

**Comment by kittiu** [comment]
Moved https://github.com/OCA/reporting-engine/pull/355

**Pull request closed without merging**
