### PR TITLE
[BCP] queue_job: standalone jobrunner from 14.0 to 11.0

### PR DESCRIPTION
**Pull request by thomaspaulb**
Backport of: https://github.com/OCA/queue/pull/409

### CODE REVIEW

**Comment by thomaspaulb** [comment]
I can't get this to run with `env ODOO_RC=odoo.cfg python -m odoo.addons.queue_job.jobrunner` like the original PR mentions, I get:

```
/home/nightly/odoo/.venv/bin/python: Error while finding module specification for 'odoo.addons.queue_job.jobrunner' (ModuleNotFoundError: No module named 'odoo.addons.queue_job')
```

It only works with: `env ODOO_RC=auto/odoo.conf python -c "import odoo; odoo.tools.config.parse_config(); from odoo.addons import queue_job; runner = queue_job.jobrunner.QueueJobRunner.from_environ_or_config(); runner.run()"`

**Comment by sbidoul** [comment]
> I can't get this to run with env ODOO_RC=odoo.cfg python -m odoo.addons.queue_job.jobrunner

Ah, yes. You likely have the `queue` repo in odoo.cfg addons_path. Therefore `odoo.addons.queue_job` is not known to the python import machinery until `odoo.tools.config.parse_config` has run, so `python -m` can't possibly find it.

Things you can do:
* install this queue_job PR with pip: `pip install git+https://github.com/oca/queue@refs/pull/456/head#subdirectory=setup/queue_job`. That will install it in `site-package`, hence in `sys.path`.
* add `queue/setup/queue_job` in `PYTHONPATH` (there is `odoo/addons/queue_job` there) -- although don't rely on that, since this setup directory will likely disappear in the future, so I just mention it as it may help explaining the mechanism.
* or, run `__main__.py` as a script: `python queue/queue_job/job_runner/__main__.py`

**Comment by sbidoul** [comment]
There are two unrelated commits in this PR?

**Comment by thomaspaulb** [comment]
@sbidoul 

- I went for just putting the long `python -c` command in my jobrunner service, are the methods you mention better in some way? (except for being more elegant)

- The commits are not unrelated, they are commits that I cherry-picked from the `14.0` branch that are required for it to work

**Comment by sbidoul** [comment]
> are the methods you mention better in some way? (except for being more elegant)

Running `__main__.py` as a script avoids some minor code duplication in your job runner service. Otherwise, they should be equivalent at runtime.

**Review by sbidoul — APPROVED** [review]

**Review by guewen — APPROVED** [review]

**Pull request merged**
