### PR TITLE
[14.0][IMP] queue_job: use a widget in eta field in queue job tree view

### PR DESCRIPTION
**Pull request by fernandahf**
Description of the issue/feature this PR addresses:

There is no issue, otherwise an improvement in queue job tree view, in order to user identifies clearly remaining days of `ETA` of queue job (in case of have ETA)

Screen Shot 2021-11-04 at 11 35 36

Also, this PR disables lint `duplicate-xml-fields` due to in v14.0 is allowed.

Current behavior before PR:
Queue job tree view showing `ETA` field with datetime.

Desired behavior after PR is merged:
Queue job tree view showing `ETA` field with remaining days widget, user can see clearly remaining days to the job is executed.

-- I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
If the remaining time is less a day, are hours displayed as well?

**Comment by fernandahf** [comment]
it's showing `Today`:

Screen Shot 2021-11-04 at 12 11 59

cc @moylop260

**Comment by pedrobaeza** [comment]
I think that limits a bit the usefulness, as you want to see the exact hour for being executed, but I let the rest to give their opinion.

**Comment by guewen** [comment]
It would be nice if it shows "in 4 minutes", but I find Today too large. Having the information that a job is executed in 22 or 24 days is not really decisive, but in 2 minutes or 6 hours is.

So I don't find this to be an improvement.

I like the idea though and thanks for proposing it.

**Comment by guewen** [comment]
Oh I didn't see it was beside the other one. So my only concern is the place it takes. Maybe add a visibility? hidden by default?

**Comment by fernandahf** [comment]
@guewen 

I hid the field by default.

cc @moylop260

**Review by guewen — APPROVED** [review]
Thanks!

**Comment by fernandahf** [comment]
@guewen 

There is an error in `Actions` of PR related to a dependency:

https://github.com/vauxoo-dev/queue/runs/4156961482?check_suite_focus=true

`AttributeError: module 'collections' has no attribute 'MutableSet'`

Could you review it, please?

cc @moylop260

**Comment by fernandahf** [comment]
@guewen 

Is there something to do with my side in this PR?

**Comment by guewen** [comment]
No, I was waiting for a second review as we are supposed to do.

Sorry for the inconvenience and thank you for your PR

/ocabot merge minor

**Pull request merged**
