### PR TITLE
[15.0] [IMP] `queue_job`: bump app icon style

### PR DESCRIPTION
**Pull request by ivantodorovich**
Closes https://github.com/OCA/queue/issues/457

@pedrobaeza @guewen @simahawk

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Odoo icons have 140x140px. Why putting another different size that may have blur problems?

**Comment by ivantodorovich** [comment]
> Odoo icons have 140x140px. Why putting another different size that may have blur problems?

Updated the png to 140px.
On the enterprise UI they're displayed at 70px (I think it's the same with OCA web_responsive). I'm not sure why odoo stores them at 140px, but let's be consistent 👍🏻

**Review by pedrobaeza — APPROVED** [review]
In `web_responsive`, they are shown at 72x72.

**Review by etobella — APPROVED** [review]

**Review by baimont — APPROVED** [review]

**Review by guewen — APPROVED** [review]
Thanks for your work!

**Pull request merged**
