### PR TITLE
[IMP] - keep connexion alive in case of job inactivity

### PR DESCRIPTION
**Pull request by agent-z28**
Solves #246 by backporting https://github.com/OCA/queue/pull/249

### CODE REVIEW

**Comment by guewen** [comment]
Thanks. Can you keep the authorship of the commit please? Usually, a `git cherry-pick` keeps proper information.

**Comment by guewen** [comment]
Done in #257

**Comment by guewen** [comment]
No, different version.

**Comment by agent-z28** [comment]
@guewen please check again

**Pull request closed without merging**
