### PR TITLE
[RFC] jobrunner cli

### PR DESCRIPTION
**Pull request by sbidoul**
~/!\ This is very rough and mostly untested. So just an idea so far.~

I wonder if running the job runner in a standalone process could be a solution to the problem of running a single job runner in a multi-node deployment.

We could then let the responsibility of running one replica of the job runner to the orchestrator (say, k8s), and we don't need ensure it's a singleton ourselves.

Use with `env ODOO_RC=odoo.cfg python -m odoo.addons.queue_job.jobrunner`.

### CODE REVIEW

**Comment by sbidoul** [comment]
With this, there is no need for queue_job in server_wide_modules.

**Comment by sbidoul** [comment]
This seems to work well in our first tests. I think we can merge this as it is non-intrusive. I'll document it when we have more experience in production.

**Review by guewen — APPROVED** [review]
Very good indeed for k8s-style infrastructure. Thanks!
We've run full loop with the old odoo-job-runner start script (don't remember the exact name) :laughing:

**Pull request merged**
