### PR TITLE
[16.0] queue_job: Forward port queue dependencies from 15.0

### PR DESCRIPTION
**Pull request by lmignon**

### CODE REVIEW

**Comment by lmignon** [comment]
ping @guewen @simahawk 
The JobDirectGraph widget has been migrated to owl since the legacy mode didn't work on odoo 16

**Comment by lmignon** [comment]
I'll redo the forward port...

**Comment by guewen** [comment]
> The JobDirectGraph widget has been migrated to owl since the legacy mode didn't work on odoo 16

Cool! I did a quick try to adapt the widget to owl but couldn't finalize :)

**Review by guewen — APPROVED** [review]
Thanks for the port!

**Comment by lmignon** [comment]
@guewen I encouter a strange error when using 'delayable()' on a recordset. The `_job_method`  is filled at the end of the call to `delayable` with `<bound method BaseModel.__len__ of product.product(57,)>` :thinking: :astonished:

**Comment by lmignon** [comment]
> @guewen I encouter a strange error when using 'delayable()' on a recordset. The `_job_method` is filled at the end of the call to `delayable` with `<bound method BaseModel.__len__ of product.product(57,)>` thinking astonished

The problem is only when I try to debug the test :sob:

**Comment by guewen** [comment]
Could it be related to the same issue reported here? https://github.com/OCA/queue/pull/440

**Comment by lmignon** [comment]
No it's not. I suspect a side effect between the debugger and de override of `__getattr__` into `Delayable`....

**Review by rousseldenis — APPROVED** [review]
LGTM

**Pull request merged**
