### PR TITLE
[16.0][FW] queue_job: multiple ports from 14.0

### PR DESCRIPTION
**Pull request by baimont**
Port of the following PRs from 14.0 to 16.0:
- #443 
- #453

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is not changing anything right now. What is needed AFAIK is the module dependency, but not the server_wide_modules change.

**Comment by baimont** [comment]
> This is not changing anything right now. What is needed AFAIK is the module dependency, but not the server_wide_modules change.

I'll adapt soon

**Review by sbidoul — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]
yes it changed the README and changed it back again, but this was done with these 2 steps in v14 so I think it's okay to just cherry-pick the  2 commits the way it is done in this PR.

**Pull request merged**
