### PR TITLE
[MIG][15.0] queue_job_cron to version 15.0

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Standard migration to version 15.0

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by simahawk — APPROVED** [review]
LG

**Comment by AaronHForgeFlow** [comment]
I think the CI failed because of an infrastructure thing. Probably retrying the merge will succeed. Can you do so @simahawk ?

**Pull request merged**
