### PR TITLE
[IMP] queue: Add icon

### PR DESCRIPTION
**Pull request by pedrobaeza**

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Review by guewen — APPROVED** [review]
Yeay :fireworks: 
Thanks!

**Comment by guewen** [comment]
travis is having some issues right now, I will rerun the build later

**Review by lasley — APPROVED** [review]

**Comment by lasley** [comment]
Travis red due to https://github.com/OCA/maintainer-quality-tools/pull/450

IMO this is safe to merge with a red CI. Anyone agree?

**Comment by pedrobaeza** [comment]
I think so.

**Comment by guewen** [comment]
Merged then!

**Comment by lasley** [comment]
It's pretty lame how happy it just made me to see the new icons in my Odoo instance. I felt this was a necessary thing to report 🚀

**Comment by pedrobaeza** [comment]
I'm glad to make you happy :smile:

**Pull request merged**
