### PR TITLE
[WIP] 11.0 Port jobrunner as a worker

### PR DESCRIPTION
**Pull request by guewen**
From @StefanRijnhart's https://github.com/OCA/connector/pull/288

This is an early untested PR.

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
no test, LG

**Review by simahawk — CHANGES_REQUESTED** [review]
but tests would be nice to have, at least on initialization

**Comment by simahawk** [comment]
early review: missed [WIP] in title :stuck_out_tongue:

**Comment by zakiuu** [comment]
Hi @guewen, just checking on any updates about this PR?

**Comment by guewen** [comment]
Hi @zakiuu, I could not spend time on this unfortunately :-(

**Comment by zakiuu** [comment]
you can list the remaining things you wanted to add , and I'll take care of it with you permission of corse.

**Comment by guewen** [comment]
IIRC I started it by picking the changes from 07cca55 but never actually tested it.
So, that would mostly be about testing with enough jobs and leave it running long enough. I wanted to see how it reacts when a memory limit is reached on the jobrunner's worker too.

If you want to take over from there, I would highly appreciate of course :)

**Pull request closed without merging**
