### PR TITLE
[14.0][IMP] queue_job: identity_key enhancements

### PR DESCRIPTION
**Pull request by simahawk**
Replaces https://github.com/OCA/queue/pull/544

@richard-willdooit sorry, I really need to move this fwd on both 14 and 16.
I kept your commit here and I just dropped the odoo version from the msg.
I also added a specific commit to drop the STARTED state to make prominent the motivation provided by @guewen on https://github.com/OCA/queue/pull/546/files#r1232041609 (whole comment in the commit description).

I can fwd port to v16 later.

### CODE REVIEW

**Comment by simahawk** [comment]
I've created https://github.com/OCA/queue/issues/582 to follow up w/ the option to make states configurable per job.

**Comment by guewen** [comment]
Thanks! (To @richard-willdooit too)

**Review by guewen — APPROVED** [review]

**Comment by simahawk** [comment]
Build fixed on #583

**Pull request merged**
