### PR TITLE
[12.0][IMP] queue_job: track error in chatter

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
When job fails, it shows in chatter:

Selection_2215

Later, the job does a retry. If the retry succeeds, the error is deleted. If not succeeds but the error is different, the error changes. In both cases, you cannot know what was the first error. Let's put in the chatter to have better history.

### CODE REVIEW

**Review by PCatinean — APPROVED** [review]

**Comment by PCatinean** [comment]
I second this, db size should not be an issue with the autovacuum and exception info is indeed quite important

**Comment by MiquelRForgeFlow** [comment]
@simahawk @guewen please! Once merged, I will do forward ports...

**Review by etobella — APPROVED** [review]
Technically LGTM

**Review by simahawk — APPROVED** [review]
LG. Next time pls, move the pre-commit update to another PR :pray:

**Pull request merged**
