### PR TITLE
Support encoding/decoding lxml.etree objects

### PR DESCRIPTION
**Pull request by PCatinean**

### CODE REVIEW

**Comment by guewen** [comment]
Hey @PCatinean, thanks. Looks good, could you check linting with pre-commit?

**Comment by PCatinean** [comment]
@guewen updated

**Review by simahawk — DISMISSED** [review]
LG

**Comment by PCatinean** [comment]
I need to add tests, give me a few minutes

**Comment by simahawk** [comment]
> I need to add tests, give me a few minutes

I was about to rollback my approval for this, indeed :smile:

**Comment by PCatinean** [comment]
Done

**Review by guewen — APPROVED** [review]
Yeaahh tests! Thanks :)

**Review by simahawk — APPROVED** [review]

**Pull request merged**
