### PR TITLE
14.0 fix queue job cron jobrunner

### PR DESCRIPTION
**Pull request by petrus-v**

### CODE REVIEW

**Review by alexandregaldeano — APPROVED** [review]
LGTM

**Review by sbidoul — APPROVED** [review]
Given the documentation of the ChannelJob class, this fix looks correct

```
    Channel jobs are comparable according to the following rules:
        * jobs with an eta come before all other jobs
        * then jobs with a smaller eta come first
        * then jobs with a smaller priority come first
        * then jobs with a smaller creation time come first
        * then jobs with a smaller sequence come first
```

**Comment by sbidoul** [comment]
cc/ @simahawk

**Comment by dreispt** [comment]
@simahawk care to review?

**Comment by petrus-v** [comment]
Hi @ivantodorovich ! I hope this finds you well :)

As you are the maintainer of this module do you mind to review and merge it if you're fin with it ?

**Review by simahawk — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
