### PR TITLE
[15.0][MIG] Migration of queue_job_subscribe

### PR DESCRIPTION
**Pull request by lembregtse**

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@lembregtse     "installable": False? Is this on purpose?

**Comment by luisg123v** [comment]
Hi @lembregtse,

Is this abandoned?

CC @tomeyro @frahiklv @desdelinux

**Comment by lembregtse** [comment]
@luisg123v no, I somehow missed the feedback on the PR.

@CasVissers-360ERP I just migrated the module and went through the steps, I did not modify that parameter. But I have removed it nevertheless. Thanks.

**Review by luisg123v — CHANGES_REQUESTED** [review]
- Missing OCA's standard README structure. You can check the template [here](https://github.com/OCA/maintainer-tools/tree/master/template/module/readme) and re-generate module's README running commands depicted [here](https://github.com/OCA/maintainer-tools/#readme-generator)
- You seem to be adding an extra commit other than the migration one, there should be only one. If you consider changes there are actually required, maybe you should squash them


CC @moylop260

**Comment by SilvioC2C** [comment]
Hello @lembregtse,
any chance you can resolve the conflicts and address @luisg123v last comments?

I was planning to migrate this module on my own, but then I found this PR, so I'd like to avoid duplicates and help you if I can!

**Comment by SilvioC2C** [comment]
Hello @lembregtse,
I've duplicated this PR (see https://github.com/OCA/queue/pull/445), and it has been merged yesterday afternoon.
I think you can close this one.

**Pull request closed without merging**
