### PR TITLE
queue_job_cron: do not require read access to ir.cron

### LINKED ISSUE #48: User in cron-job needs read-right ir.cron document after install of queue_job_cron
Before installing queue_job_cron the user running the cron job could be anyone who had the access rights to the object of the job. After installing the user also needs read rights to ir.cron. This is irrespective of how the job is running, job_queue or not. Is this on purpose?

### PR DESCRIPTION
**Pull request by sbidoul**
fixes #48

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Shouldn't the job should be run with the user specified in the cron?

**Comment by sbidoul** [comment]
@pedrobaeza I think it does, see https://github.com/OCA/queue/issues/48#issuecomment-364058572.

This sudo is only to read the ir.cron properties (ie the channel name), not to run it.

**Review by pedrobaeza — APPROVED** [review]
OK, thanks for the clarification. As always, it would be desirable a version bump

**Review by simahawk — APPROVED** [review]

**Review by guewen — APPROVED** [review]

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by sbidoul** [comment]
Merged and bumped version.

**Pull request merged**
