### PR TITLE
[15.0][MIG] queue_job_batch, test_queue_job_batch: Migration to 15.0

### PR DESCRIPTION
**Pull request by amh-mw**

### CODE REVIEW

**Comment by amh-mw** [comment]
@agenterp Since you noticed the lack of this module in the 15.0 milestone, mind giving it a review?

**Comment by amh-mw** [comment]
@jans23 Would you mind reviewing this pull request?

**Comment by jans23** [comment]
Ok, will put it on our team's task list.

**Comment by alihashaam** [comment]
@amh-mw 

There is a small issue with the way qweb is referenced in manifest file of queue_job_batch module of this PR.

as if you look in the base modules, it should be done as follow. This solved the error [1] for me as otherwise I was getting the error [1] that :

[1] Qweb template "queue_job_batch.view.Menu" not found

`"assets": {
        "web.assets_qweb": [
            "queue_job_batch/static/src/xml/systray.xml",
        ],
  `
  
  I would like to push this change but I dont have access to repo. How would you prefer I proceed?

**Comment by alihashaam** [comment]
@amh-mw 

Please find our work in PR:
https://github.com/amh-mw/queue/pull/1

@jans23 the module was also reviewed and two other small changes were included in above PR.

**Comment by amh-mw** [comment]
@alihashaam Thanks for the help!

**Comment by amh-mw** [comment]
Reopened as #633

**Pull request closed without merging**
