### PR TITLE
[12.0][FIX] retry_postpone TransactionRollback

### PR DESCRIPTION
**Pull request by liweijie0812**
The transaction rollback causes the execution of the retry_postpone method to also be rolled back

### CODE REVIEW

**Comment by liweijie0812** [comment]
11.0 12.0 version has this problem

**Comment by guewen** [comment]
Do you think it is similar to #120?

**Comment by liweijie0812** [comment]
> Do you think it is similar to #120?   I haven't touched this yet.
But now the retry_postpone method has a lot of errors.
After I changed the retry method, there was no failure.

**Comment by liweijie0812** [comment]
Same as this #41

**Comment by sbidoul** [comment]
@liweijie0812 do you have a full python 3 stack trace of such a situation (including nested exceptions)?

**Comment by liweijie0812** [comment]
> @liweijie0812 do you have a full python 3 stack trace of such a situation (including nested exceptions)?

psycopg2.extensions.TransactionRollbackError: deadlock detected
DETAIL:  Process 19581 waits for ShareLock on transaction 15488433; blocked by process 19568.
Process 19568 waits for ShareLock on transaction 15488432; blocked by process 19581.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (27,58) in relation "maintenance_equipment"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ci/localtest/erp/odoo_third/queue_job/controllers/main.py", line 105, in runjob
    seconds=PG_RETRY)
  File "/ci/localtest/erp/odoo_third/queue_job/controllers/main.py", line 87, in retry_postpone
    job.store()
  File "/ci/localtest/erp/odoo_third/queue_job/job.py", line 514, in store
    db_record = self.db_record()
  File "/ci/localtest/erp/odoo_third/queue_job/job.py", line 538, in db_record
    return self.db_record_from_uuid(self.env, self.uuid)
  File "/ci/localtest/erp/odoo_third/queue_job/job.py", line 352, in db_record_from_uuid
    record = model.search([('uuid', '=', job_uuid)], limit=1)
  File "/ci/localtest/erp/release/odoo_for_ci/20181115-142805/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/ci/localtest/erp/release/odoo_for_ci/20181115-142805/odoo/models.py", line 3791, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/ci/localtest/erp/release/odoo_for_ci/20181115-142805/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/ci/localtest/erp/release/odoo_for_ci/20181115-142805/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

**Comment by liweijie0812** [comment]
psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ci/localtest/erp/odoo_third/queue_job/controllers/main.py", line 105, in runjob
    seconds=PG_RETRY)
  File "/ci/localtest/erp/odoo_third/queue_job/controllers/main.py", line 87, in retry_postpone
    job.store()
  File "/ci/localtest/erp/odoo_third/queue_job/job.py", line 514, in store
    db_record = self.db_record()
  File "/ci/localtest/erp/odoo_third/queue_job/job.py", line 538, in db_record
    return self.db_record_from_uuid(self.env, self.uuid)
  File "/ci/localtest/erp/odoo_third/queue_job/job.py", line 352, in db_record_from_uuid
    record = model.search([('uuid', '=', job_uuid)], limit=1)
  File "/ci/localtest/erp/release/odoo_for_ci/20181115-142805/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/ci/localtest/erp/release/odoo_for_ci/20181115-142805/odoo/models.py", line 3791, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/ci/localtest/erp/release/odoo_for_ci/20181115-142805/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/ci/localtest/erp/release/odoo_for_ci/20181115-142805/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

**Comment by CasVissers-360ERP** [comment]
I can confirm the issue, will try to confirm this fix repairs it.

**Comment by kingofsevens** [comment]
I can confirm that issue is there and v10 fix also applies to v11. We are not receiving any more concurrency errors on the jobs. But sometimes we are receiving some errors on the partners as both jobs try to access a specific partner but it seems the job is set to retry.

**Review by guewen — APPROVED** [review]
Reproduced and tested

**Review by simahawk — APPROVED** [review]

**Review by CasVissers-360ERP — APPROVED** [review]
Fix also worked here.

**Comment by CasVissers-360ERP** [comment]
Shouldn't this also be done for v11?

**Comment by guewen** [comment]
@CasVissers https://github.com/OCA/queue/pull/142

**Pull request merged**
