### PR TITLE
[14.0][IMP] queue_job: track error in chatter (forward port)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/queue/pull/597.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't that message very long to be put there?

**Comment by MiquelRForgeFlow** [comment]
Not necessarily.It is not the full traceback, just the error message.

**Review by pedrobaeza — APPROVED** [review]
OK, although I'm not very sure it will be helpful without the full trace if the error is for example just `ValidationError`.

**Review by PCatinean — APPROVED** [review]

**Review by guewen — APPROVED** [review]

**Pull request merged**
