### PR TITLE
[12.0] Use more permissive license AGPL3 → LGPL3

### PR DESCRIPTION
**Pull request by guewen**
This change has been done and accepted on the component and connector
addons: https://github.com/OCA/connector/pull/356

This is a low-level technical module, we may need to use jobs on
enterprise features.

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Review by lmignon — APPROVED** [review]
Thank you @guewen

**Review by sbidoul — APPROVED** [review]

**Comment by guewen** [comment]
I'll rebase when https://github.com/OCA/queue/pull/186 is merged

**Comment by guewen** [comment]
Rebased

**Comment by guewen** [comment]
retry:

/ocabot merge

**Pull request merged**
