### PR TITLE
[12.0][IMP] - keep connexion alive in case of job inactivity

### PR DESCRIPTION
**Pull request by sbejaoui**
fixes: #246

### CODE REVIEW

**Comment by guewen** [comment]
@sbejaoui Is my understanding correct that it will wait for notifications 60 seconds, then if nothing happened, execute the keep-alive and listen again for 60 seconds?

**Comment by sbejaoui** [comment]
> @sbejaoui Is my understanding correct that it will wait for notifications 60 seconds, then if nothing happened, execute the keep-alive and listen again for 60 seconds?

yes that's the point

**Review by guewen — APPROVED** [review]
Thanks @sbejaoui

**Review by sbidoul — APPROVED** [review]

**Pull request merged**
