### PR TITLE
[14.0][MIG] - queue_job_subscribe

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by BT-cserra — APPROVED** [review]

**Comment by BT-cserra** [comment]
Hello @sbejaoui do you have time to merge the conflicts so that this can be merged? I can propose a PR on your branch to fix them if this is more convenient for you. Thanks.

**Comment by sbejaoui** [comment]
> Hello @sbejaoui do you have time to merge the conflicts so that this can be merged? I can propose a PR on your branch to fix them if this is more convenient for you. Thanks.

Hi @BT-cserra , it's fixed now

**Comment by BT-cserra** [comment]
> > Hello @sbejaoui do you have time to merge the conflicts so that this can be merged? I can propose a PR on your branch to fix them if this is more convenient for you. Thanks.
> 
> Hi @BT-cserra , it's fixed now

Many thanks :)

**Review by BT-aestebanez — APPROVED** [review]

**Comment by BT-cserra** [comment]
Hello @rousseldenis can you please trigger a merge on this one if it's fine for you?

**Comment by rousseldenis** [comment]
> Hello @rousseldenis can you please trigger a merge on this one if it's fine for you?

Unfortunately, don't have power here :-)

@OCA/core-maintainers

**Comment by guewen** [comment]
What is this error?

/ocabot merge nobump

**Comment by BT-cserra** [comment]
@rousseldenis @dreispt @guewen many thanks!

**Comment by rousseldenis** [comment]
> What is this error?
> 
> /ocabot merge nobump

That's a bug reported recently as GitHub API access rights has changed.

**Pull request merged**
