### PR TITLE
[14.0] Add graph of dependencies

### PR DESCRIPTION
**Pull request by guewen**
Migration of #154, details on the link.

You can test enqueuing a graph a jobs with test jobs by going on the runboat instance and doing a request on `/queue_job/create_test_job?size=30` that will generate a random graph of 30 jobs. Jobs are not executed, but you can look at the dependency graphs ;)

### CODE REVIEW

**Comment by guewen** [comment]
Hi @simahawk @sbidoul, okay to merge this?

**Review by simahawk — APPROVED** [review]
Skimmed quickly through it, can't find anything bad... but I trust you did your homework :stuck_out_tongue_winking_eye: 

COOOOL THANKS!

**Comment by sbidoul** [comment]
I totally trust the author credentials :)

**Pull request merged**
