### PR TITLE
[WIP] [FIX] [14.0] restore doctest testing in 14.0

### PR DESCRIPTION
**Pull request by PieterPaulussen**
Cfr this PR on 13.0: https://github.com/OCA/queue/pull/296

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the port!

**Comment by PieterPaulussen** [comment]
@StefanRijnhart All tests were successful so this means my hypothesis is correct that failed doctests are currently not registred by this implementation!

**Comment by StefanRijnhart** [comment]
Great opportunity for a bugfix, leading to fame, and possible fortune in the financial and romantic domains!

**Comment by PieterPaulussen** [comment]
Closing in favour of: https://github.com/OCA/queue/pull/338

**Pull request closed without merging**
