### PR TITLE
[15.0][MIG] 'queue_job' module

### PR DESCRIPTION
**Pull request by romi477**

### CODE REVIEW

**Comment by ventor-dev** [comment]
@pedrobaeza looks like workflow is not running, because @romi477 is first time contributor. Could you, please, check and approve workflows?

**Review by ventor-dev — APPROVED** [review]

**Comment by ventor-dev** [comment]
@guewen could you, please, review and approve

**Review by guewen — APPROVED** [review]
Thanks for the work!

**Comment by ventor-dev** [comment]
@guewen I guess you need to merge it now?

**Comment by guewen** [comment]
@ventor-dev usually in this repository, we keep the branch and set modules as uninstallable, I didn't had the opportunity to prepare the branch this way. I'm about to force-push the branch to restore the history, then, I cherry-picked your commits in a new branch. I'll open a PR with this branch to check the CI.

**Comment by guewen** [comment]
BTW, I didn't see before, you missed the module `test_queue_job` which is necessary to ensure everything is working correctly

**Comment by pedrobaeza** [comment]
Note that this flow is an exception made by the maintainers of this repository, not the usual OCA flow.

**Pull request closed without merging**
