### PR TITLE
[17.0][MIG] queue_job + test_queue_job: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
Ref: BSRD-729

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please cherry-pick https://github.com/OCA/queue/commit/dafdf0a258808ad8a51fcbc9616a42d034549bac

**Comment by romi477** [comment]
In my opinion, everything is good, except maybe the method _patch_job_auto_delay, which should work in conjunction with the standard method _patch_method, which has been removed from the base model. For this module, it's not a big issue, but for example, the module test_queue_job won't work without _patch_method.

**Comment by nguyenminhchien** [comment]
> In my opinion, everything is good, except maybe the method _patch_job_auto_delay, which should work in conjunction with the standard method _patch_method, which has been removed from the base model. For this module, it's not a big issue, but for example, the module test_queue_job won't work without _patch_method.

@romi477 updated

**Comment by nguyenminhchien** [comment]
> Please cherry-pick [dafdf0a](https://github.com/OCA/queue/commit/dafdf0a258808ad8a51fcbc9616a42d034549bac)

@MiquelRForgeFlow picked

**Review by gurneyalex — APPROVED** [review]

**Comment by simahawk** [comment]
I think you miss the 2nd commit from https://github.com/OCA/queue/pull/587
TIP: use oca-port to check that we do not miss any PR and finally get a blacklist of the PR that are ported already.

**Comment by nguyenminhchien** [comment]
> I think you miss the 2nd commit from #587 TIP: use oca-port to check that we do not miss any PR and finally get a blacklist of the PR that are ported already.

No, i didn't. it's here 
image

**Comment by ventor-dev** [comment]
@guewen could you please check it? (or somebody)

**Comment by sanderlienaerts** [comment]
Please note that the following deprecation warning occurs in Odoo 17:  `DeprecationWarning: XML declarations in HTML module descriptions are deprecated since Odoo 17, queue_job can just have a UTF8 description with not need for a declaration.
`

Triggered by line 1 in [queue_job/static/description/index.html](https://github.com/nguyenminhchien/queue/blob/17.0-mig-queue_job/queue_job/static/description/index.html)

**Comment by nguyenminhchien** [comment]
> Please note that the following deprecation warning occurs in Odoo 17: `DeprecationWarning: XML declarations in HTML module descriptions are deprecated since Odoo 17, queue_job can just have a UTF8 description with not need for a declaration. `
> 
> Triggered by line 1 in [queue_job/static/description/index.html](https://github.com/nguyenminhchien/queue/blob/17.0-mig-queue_job/queue_job/static/description/index.html)

fixed, tks.

**Comment by ventor-dev** [comment]
Can it be merged? Or smth else is missing?

**Comment by AlexanderPashuk** [comment]
@guewen can we help somehow to finish migration of this module?

**Review by guewen — APPROVED** [review]
Thanks for your work!

**Comment by okuryan** [comment]
@pedrobaeza can you (or who is responsible?) publish it on Odoo App store?

**Comment by MiquelRForgeFlow** [comment]
> publish it on Odoo App store?

It's automatic, there is a "cron" that updates that periodically.

**Comment by pedrobaeza** [comment]
Someone from board should do it.

**Comment by simahawk** [comment]
I can have a look

**Comment by simahawk** [comment]
image

**Pull request merged**
