### PR TITLE
[16.0][MIG] base_export_async: Migration to 16.0

### PR DESCRIPTION
**Pull request by bencoronel**

### CODE REVIEW

**Comment by asierneiradev** [comment]
Hi @guewen @sbidoul @ivantodorovich ,

Someone can take a look at the proposed PR.

Thank you very much,
best regards

**Comment by kikopeiro** [comment]
Hi @vincent-cowboy @amh-mw ,  could you take a look to this PR?

Thanks!

**Review by kikopeiro — APPROVED** [review]
LGTM (without code review)
:+1:

**Review by amh-mw — APPROVED** [review]

**Comment by julenfl** [comment]
Hi @guewen @sbidoul @ivantodorovich ,

Could someone please merge this PR, it seems correct

Thank you

**Comment by guewen** [comment]
Thanks for the work!

**Pull request merged**
