### PR TITLE
[14.0] Migration of queue_job

### PR DESCRIPTION
**Pull request by guewen**
Hi,

Several PRs have already been opened for this migration: #263, #286, #288. Thanks a lot to @eantones, @sebastienbeau, @dnplkndll for them, as the result here is a joint work for the migration.

As the runbot build was still red on these PRs (the missing part was https://github.com/OCA/queue/pull/286#issuecomment-734686444), I opened yet a new one... As we switch the version, I took the opportunity to add a few more commits:

* Adapt the `JobSerialized` field for 14.0 (fix the warnings in runbot)
* Remove migration scripts for 13.0
* Split the models and views in individual files
* Fixed a few errors detected by manual testing
* Add import shortcut for `identity_exact` (`from odoo.addons.queue_job import identity_exact`)

Some commits have details in their body.

I hope the runbot build will now be green, and we'll be able to merge quickly :crossed_fingers:.

@eantones, @sebastienbeau, @atchuthan, @CasVissers-360ERP, @t-900-a, @aliencrash, @dnplkndll, @bealdav as you all participated in the previous pull requests, in code, comments, tests, reviews, I thank you one more time for your help (it feels good to have your support), if you can review my last changes and put your approvals, we can merge this fast.

### CODE REVIEW

**Comment by guewen** [comment]
Green! :green_circle:

**Review by simahawk — APPROVED** [review]
Just code review. LG!

**Review by eantones — APPROVED** [review]
Thank you for all the improvements. LGTM!

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test! 👍

**Pull request merged**
