### PR TITLE
[ADD] queue_job module: migration from 9.0

### PR DESCRIPTION
**Pull request by cubells**
These changes are needed to upgrade connector module to 10.0

cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]

**Comment by lasley** [comment]
Curious - what's the rationale behind including the major version migrations here vs OpenUpgrade? If it's something fully supported by OCA, we migrate in the module?

**Comment by pedrobaeza** [comment]
It's simple, this should be executed when this module gets upgraded. We can't include this in OpenUpgrade if we want to keep the modularity, or we will fill OpenUpgrade with a lot of `if openupgrade.is_module_installed(...` and the logic will be more complicated, as we must know where is the proper place to perform the upgrade.

**Comment by lasley** [comment]
Totally makes sense, thanks Pedro

**Comment by lmignon** [comment]
@pedrobaeza @cubells @rafaelbn You must revert this merge! The queue_job addon doesn't depend on 'connector' and don't exist in 9.0.

**Comment by pedrobaeza** [comment]
This is for 10.0, not for 9.0.

**Comment by guewen** [comment]
@pedrobaeza yes but how would that work? queue_job is a new addon in 10.0 so you'd install it and the migration won't be called. And if it is called you might not have the `connector` addon in your setup and you shouldn't be forced to use it because you are using `queue_job`.

**Comment by pedrobaeza** [comment]
This will only be activated on migrations, not on regular installation, so there's no problem.

**Pull request merged**
